#! /usr/bin/php
<?php

namespace APPointer\Command;

require_once __DIR__ . '/src/bootstrap.php';

use APPointer\Command\APPointCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new APPointCommand());
$application->run();
