services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    APPointer\Lib\:
        resource: '../src/Lib/*'

    APPointer\Constraints\:
        resource: '../src/Constraints/*'

    APPointer\Parser\:
        resource: '../src/Parser/*'

    APPointer\Constraints\DateStringNormalizerValidator:
        class: APPointer\Constraints\DateStringNormalizerValidator
        tags:
            - { name: 'validator.constraint_validator', alias: 'date.string.normalizer.validator' }
